package config;

import config.yaml.CustomerConfig;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.InputStream;

/**
 * Reads configuration.
 */
public class ConfigReader {

    private static final String PROPERTIES_FROM_POM_PROPERTIES = "properties-from-pom.properties";

    /**
     * Reads current build customer configuration.
     *  <ol>
     *    <li> configuration file name from pom.xml pom-property-customer, eg. customer1. </li>
     *    <li> configuration files should be in main/resources/customers/<pom-property-customer>.yaml, e.g. customer1.yaml. </li>
     *  </ol>
     */
    public static CustomerConfig getCustomerConfig() {
        String customerConfigFileName = null;
        String customerPomProperty = null;
        try {
            customerPomProperty = getCustomerPomProperty();
            customerConfigFileName = "customers/" + customerPomProperty + ".yaml";
            return new ConfigReader().getCustomerConfig(customerConfigFileName);
        } catch (Exception e) {
            throw new RuntimeException("Could not find customer file=" + customerConfigFileName + ". " +
                    "The customer name is generated by the maven build from " +
                    "pom.xml property customer=<" + customerPomProperty +">", e);
        }
    }

    /**
     * Reads configuration file name from pom.xml property customer.
     */
    static String getCustomerPomProperty() throws IOException {
        PropertiesReader reader = new PropertiesReader(PROPERTIES_FROM_POM_PROPERTIES);
        return reader.getProperty("customer");
    }

    /**
     * Reads yaml customer configuration.
     */
    CustomerConfig getCustomerConfig(String configFileName) {
        Yaml yaml = new Yaml();
        InputStream inputStream = this.getClass()
                .getClassLoader()
                .getResourceAsStream(configFileName);
        return yaml.load(inputStream);
    }

}
